PLF-7228: Make codec file path configurable by properties
exoplatform/gatein-portal pull request #114
Opened 2017-05-15 14:52 UTC by anoissi

2017-05-16 07:13 UTC, thomasdelhomenie requested changes

2017-05-16 07:13 UTC, thomasdelhomenie commented on component/web/security/src/main/java/org/exoplatform/web/security/codec/CodecInitializer.java
> +            String codecFilePath = PropertyManager.getProperty("exo.security.rememberme.codec.file");
I think we should remove "rememberme" from the name of the property since it is not dedicated to rememberme feature.

2017-05-16 07:14 UTC, thomasdelhomenie commented
Please add unit tests also.

2017-07-04 13:59 UTC, closed without merging

2017-07-04 14:00 UTC, anoissi commented
it will be created on exodev