Add Double validator
exoplatform/gatein-portal pull request #98
Opened 2015-12-08 15:33 UTC by wkhessairi

2016-10-19 16:29 UTC, boubaker commented on webui/core/src/main/java/org/exoplatform/webui/form/validator/DoubleFormatValidator.java
> + * Copyright (C) 2009 eXo Platform SAS.
2016 instead of 2009

2016-10-19 16:30 UTC, boubaker commented on webui/core/src/main/java/org/exoplatform/webui/form/validator/DoubleFormatValidator.java
> + * Created by The eXo Platform SARL Author : Walid Khessairi wkhessairi@exoplatform.com Oct 26, 2015
Update Date

2016-10-19 16:31 UTC, boubaker commented
Please add description and update commit to add JIRA issue in title

2016-10-19 16:33 UTC, boubaker requested changes
plz update with previous comments.
Except that, the PR seems to be ok

2017-01-02 12:06 UTC, wkhessairi commented
changes done

2017-01-02 12:08 UTC, boubaker approved these changes

2017-01-03 10:57 UTC, closed without merging